kind: pipeline
name: default

steps:
- name: test
  image: node:11
  commands:
  - npm install
  - npm test

- name: Publish to NPM
  image: plugins/npm
  settings:
    username:
      from_secret: npm_username
    password:
      from_secret: npm_password
    email:
      from_secret: npm_email

- name: code-analysis
  image: aosapps/drone-sonar-plugin
  settings:
      SONAR_HOST:
        from_secret: sonar_host
      SONAR_TOKEN:
        from_secret: sonar_token
