kind: pipeline
name: default

steps:
- name: testing drone with node
  image: node
  commands:
  - npm install
  - npm test

steps:
- name: npm
  image: plugins/npm
  settings:
    username:
      from_secret: npm_username
    password:
      from_secret: npm_password
    email:
      from_secret: npm_email