language: node_js
node_js:
  - "4"
  - "5"
  - "6"
install:
  - npm install
  - npm install -g mocha
  - npm install -g jscoverage
script:
  - npm test
after_success:
- ./node_modules/.bin/jscoverage lib lib-cov
- ./node_modules/.bin/mocha test/**.js -R mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js